# Generated by Django 3.2.25 on 2025-01-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250125_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='Ingredient1', max_length=255),
        ),
    ]
